#include "Mandelbrot2.h"
#include "Mandelbrot3.h"
#include "Mandelbrot4.h"
#include "Mandelbrot5.h"
#include "Mandelbrot6.h"
#include "Mandelbrot7.h"
#include "Mandelbrot8.h"
#include "Mandelbrot9.h"
#include "Mandelbrot10.h"

#include "BurningShip2.h"
#include "BurningShip3.h"
#include "BurningShip4.h"
#include "BurningShip5.h"
